# Generated by Django 5.2.8 on 2026-05-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_parque_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='trilhas/'),
        ),
    ]
