# Generated by Django 5.2.8 on 2026-05-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_trilha_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodiversidade',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='biodiversidade/'),
        ),
    ]
